DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `proc_openChamp_WMA_getTimesPoints`(IN `runner_id` INT, INOUT `race_1` VARCHAR(32), INOUT `race_2` VARCHAR(32), INOUT `race_3` VARCHAR(32), INOUT `race_4` VARCHAR(32), INOUT `race_5` VARCHAR(32), INOUT `race_6` VARCHAR(32), INOUT `race_7` VARCHAR(32), INOUT `race_8` VARCHAR(32), INOUT `race_9` VARCHAR(32), INOUT `race_10` VARCHAR(32), INOUT `race_11` VARCHAR(32), INOUT `race_12` VARCHAR(32), INOUT `race_13` VARCHAR(32), INOUT `race_14` VARCHAR(32), INOUT `race_15` VARCHAR(32), INOUT `race_16` VARCHAR(32), INOUT `race_17` VARCHAR(32), INOUT `race_18` VARCHAR(32))
    NO SQL
BEGIN

DECLARE runner_sex VARCHAR(5);

SET runner_sex = (SELECT RunnerSex FROM tblRunners WHERE RunnerID = runner_id);

SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_1 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_1 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_2 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_2 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_3 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_3 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_4 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_4 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_5 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_5 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_6 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_6 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_7 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_7 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_8 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_8 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_9 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_9 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_10 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_10 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_11 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_11 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_12 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_12 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_13 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_13 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_14 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_14 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_15 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_15 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_16 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_16 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_17 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_17 AND tblWMARaceTimes.RunnerID=runner_id;
SELECT CONCAT(tblWMARaceTimes.RaceID, '//', tblWMARaceTimes.WMARaceTime, '//', tblOpenChampWMARacePoints.WMARacePoints) INTO race_18 FROM tblWMARaceTimes LEFT JOIN tblOpenChampWMARacePoints ON tblOpenChampWMARacePoints.RaceID = tblWMARaceTimes.RaceID AND tblOpenChampWMARacePoints.RunnerID = tblWMARaceTimes.RunnerID WHERE tblWMARaceTimes.RaceID=race_18 AND tblWMARaceTimes.RunnerID=runner_id;
/* If the query returns NULL, then the procedure will return an empty table cell '<td></td>', otherwise it will return a time '<td>45:00</td>'*/

/* good example of a loop in MySQL stored procedure:
https://stackoverflow.com/questions/14326775/call-a-stored-procedure-for-each-row-returned-by-a-query-in-mysql
*/

END$$
DELIMITER ;